development:
  secret_key_base: __pasted from rake secret___

test:
  secret_key_base: __pasted from rake secret___

production:
  secret_key_base: __pasted token from config/initializers/secret_token.rb___


